[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "cynthiateeters"
  deliveryType = "upload"
  uploadPreset = "arcane"