[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "cynthia-teeters"
  deliveryType = "upload"
  uploadPreset = "blog"
  folder = "blog-images"
  imagesPath = "/assets/blog/unsplash"
  loadingStrategy = "lazy"
