[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "cynthia-teeters"
  deliveryType = "upload"
  uploadPreset = "arcane"
  folder = "arcane"
  imagesPath = "/assets/blog/unsplash"
