[build]
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
  cloudName = "cynthia-teeters"
  deliveryType = "upload"
  uploadPreset = "blogv2"
  folder = "blogv2-images"
  imagesPath = "/assets/blog"
